import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Container from "@/components/Container";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Verification App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} text-zinc-900 bg-zinc-100 min-h-screen`}>
        <Container>
        <Header/>
          {children}
          <Footer/>
        </Container>
      </body>
    </html>
  );
}
